### ISSUE TITLE
getSources procedure problem

### ISSUE THREAD

**Issue by antkit** [w3c/tvapi#15]
> 5.3 Procedures
> 
> The getSources method when invoked MUST run the following steps:
> 
> 5.When the request has been successfully completed:
>  > 1.Let sources be the array of the retrieved TVSource elements.
>  > 2.Invoke resolver's fulfill algorithm with channels as the value argument.

I think "channels" in "2.Invoke resolver's fulfill algorithm with channels as the value argument." should be "sources".

**Comment by seanyhlin** [comment]
Fixed the typo. Thank you.
